// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsc2kCnRQErmMmxp-u97fPFThmssiJCrc',
    appId: '1:181817627578:web:c0efc3aece3ed4e1540383',
    messagingSenderId: '181817627578',
    projectId: 'pm-nesysworks',
    authDomain: 'pm-nesysworks.firebaseapp.com',
    storageBucket: 'pm-nesysworks.firebasestorage.app',
    measurementId: 'G-LDG0Q2WF2K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAAHQbRMuybLU0FZ1Tig6jb4JWsr-uDq0',
    appId: '1:181817627578:android:2085309a0ea7e111540383',
    messagingSenderId: '181817627578',
    projectId: 'pm-nesysworks',
    storageBucket: 'pm-nesysworks.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjqBVqcSB0f2pwF1jzFt8fHuok_--SwVM',
    appId: '1:181817627578:ios:4b4e24f08aec3fc6540383',
    messagingSenderId: '181817627578',
    projectId: 'pm-nesysworks',
    storageBucket: 'pm-nesysworks.firebasestorage.app',
    iosBundleId: 'kr.plinemotors.nesysworks.pmnesysworksV011204Ni',
  );
}
